---
version: '3.7'
services:
  sqlite_backup:
    image: arnaubennassar/sqlite_backup
    container_name: sqlite_backup
    restart: on-failure
    init: true
    volumes:
     - /path/to/service1:/from/service1
     - /path/to/service2:/from/service2
     - /path/to/backup:/to
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
    environment:
      - BACKUP_LIST=/from/service1/db.sqlite3:/to/service1-backup.sqlite3,/from/service2/db.sqlite3:/to/service2-backup.sqlite3
      - CRON_TIME=0 5 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0
